package com.mr3y.podcaster.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF595992)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFe2dfff)
val md_theme_light_onPrimaryContainer = Color(0xFF14134a)
val md_theme_light_secondary = Color(0xFF595992)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFe2dfff)
val md_theme_light_onSecondaryContainer = Color(0xFF14134a)
val md_theme_light_tertiary = Color(0xFF795369)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFffd8eb)
val md_theme_light_onTertiaryContainer = Color(0xFF2f1124)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFEFEDF4)
val md_theme_light_onSurface = Color(0xFF2C2C32)
val md_theme_light_surfaceVariant = Color(0xFFdbd9e0)
val md_theme_light_onSurfaceVariant = Color(0xFF47464f)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_inverseOnSurface = Color(0xFFf2f0f7)
val md_theme_light_inverseSurface = Color(0xFF2f3036)
val md_theme_light_inversePrimary = Color(0xFFc2c1ff)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFe2dfff)
val md_theme_light_outlineVariant = Color(0xFFc8c5d0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFc2c1ff)
val md_theme_dark_onPrimary = Color(0xFF2a2a60)
val md_theme_dark_primaryContainer = Color(0xFF414178)
val md_theme_dark_onPrimaryContainer = Color(0xFFe2dfff)
val md_theme_dark_secondary = Color(0xFFc2c1ff)
val md_theme_dark_onSecondary = Color(0xFF2a2a60)
val md_theme_dark_secondaryContainer = Color(0xFF414178)
val md_theme_dark_onSecondaryContainer = Color(0xFFe2dfff)
val md_theme_dark_tertiary = Color(0xFFe9b9d2)
val md_theme_dark_onTertiary = Color(0xFF47263a)
val md_theme_dark_tertiaryContainer = Color(0xFF5f3c51)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd8eb)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1D2B)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF252836)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF252836)
val md_theme_dark_onSurfaceVariant = Color(0xFF979797)
val md_theme_dark_outline = Color(0xFFC4C4C4)
val md_theme_dark_inverseOnSurface = Color(0xFF2f3036)
val md_theme_dark_inverseSurface = Color(0xFFe3e1e9)
val md_theme_dark_inversePrimary = Color(0xFF595992)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF414178)
val md_theme_dark_outlineVariant = Color(0xFF47464f)
val md_theme_dark_scrim = Color(0xFF000000)

// Source color (Liberty)
val seed = Color(0xFF525298)
