package com.mr3y.podcaster.ui.resources

data class PodcasterStrings(
    val tab_subscriptions_label: String,
    val tab_explore_label: String,
    val tab_downloads_label: String,
    val subscriptions_refresh_result_error: String,
    val subscriptions_refresh_result_mixed: String,
    val icon_menu_content_description: String,
    val icon_settings_content_description: String,
    val icon_navigate_up_content_description: String,
    val subscriptions_label: String,
    val subscriptions_empty_list: String,
    val subscriptions_episodes_empty_list: String,
    val generic_error_message: String,
    val retry_label: String,
    val currently_playing: String,
    val search_for_podcast_placeholder: String,
    val recent_searches_label: String,
    val close_label: String,
    val feed_url_incorrect_message: String,
    val search_podcasts_empty_list: String,
    val podcast_details_refresh_result_error: String,
    val podcast_details_refresh_result_mixed: String,
    val subscribe_label: String,
    val unsubscribe_label: String,
    val about_label: String,
    val episodes_label: String,
    val episode_details_refresh_result_error: String,
    val episode_details_refresh_result_mixed: String,
    val sync_work_notification_title: String,
    val sync_work_notification_body: String,
    val sync_work_notification_channel_name: String,
    val sync_work_notification_channel_description: String,
)
